package InternalFrames;

import Conexion.Dbcontext;
import Conexion.SessionHelper;
import Dialogos.dlgSeguridadPantalla;
import Dialogos.dlgSeguridadPermiso;
import Dialogos.dlgSeguridadRol;
import POJOs.Pantalla;
import POJOs.Permiso;
import POJOs.Rol;
import Utilidad.Mensajes;
import Utilidad.UtilDate;
import Utilidad.UtilTable;
import bean.PantallaBean;
import bean.PermisoBean;
import bean.RolBean;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author W4LT3R
 */
public class ifrResgistroRolesPermisos extends javax.swing.JInternalFrame {

    static RolBean rolbean = new RolBean();
    static PermisoBean permisoBean = new PermisoBean();
    static PantallaBean pantallaBean = new PantallaBean();

    static List<Rol> roles;
    static List<Permiso> permisos;
    static DefaultTableModel modelTablePermisos;

    // TABLE PANTALLAS
    static DefaultTableModel modelTablePantallas;
    static List<Pantalla> pantallas;

    /**
     * Creates new form ifrCargos
     */
    public ifrResgistroRolesPermisos() {
        initComponents();
        modelTablePermisos = (DefaultTableModel) tablePermisos.getModel();
        modelTablePantallas = (DefaultTableModel) tablePantallas.getModel();
        LoadUI();

        if (!SessionHelper.VerificarPantalla("gestion de pantallas")) {
            tabRolesPantallas.remove(pnlPantallas);
        }
        SessionHelper.VerificarPermiso(btnNuevoRol, "gestion de roles", "insertar");
        SessionHelper.VerificarPermiso(btnActualizarRol, "gestion de roles", "modificar");
        SessionHelper.VerificarPermiso(btnEliminarRol, "gestion de roles", "eliminar");

        SessionHelper.VerificarPermiso(btnNuevoPermiso, "gestion de permisos", "insertar");
        SessionHelper.VerificarPermiso(btnEditarPermiso, "gestion de permisos", "modificar");
        SessionHelper.VerificarPermiso(btnEliminarPermiso, "gestion de permisos", "eliminar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pmPermisos = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        tabRolesPantallas = new javax.swing.JTabbedPane();
        pnlRolesPermisos = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jLabel3 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        cbnRoles = new javax.swing.JComboBox<>();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        btnNuevoRol = new javax.swing.JButton();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        btnActualizarRol = new javax.swing.JButton();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        btnEliminarRol = new javax.swing.JButton();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jPanel16 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablePermisos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnNuevoPermiso = new javax.swing.JButton();
        btnEditarPermiso = new javax.swing.JButton();
        btnEliminarPermiso = new javax.swing.JButton();
        pnlPantallas = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablePantallas = new javax.swing.JTable();
        btnIngresar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");
        pmPermisos.add(jMenuItem1);

        jMenuItem2.setText("jMenuItem1");
        pmPermisos.add(jMenuItem2);

        setClosable(true);
        setIconifiable(true);
        setTitle("Gestion de Roles - Permisos");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("<html><Strong>ROLES Y PERMISOS");
        jPanel1.add(jLabel7);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.BorderLayout());

        pnlRolesPermisos.setLayout(new java.awt.BorderLayout(0, 5));

        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.LINE_AXIS));
        jPanel8.add(filler4);

        jLabel3.setText("Roles");
        jPanel8.add(jLabel3);
        jPanel8.add(filler1);

        cbnRoles.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbnRolesItemStateChanged(evt);
            }
        });
        jPanel8.add(cbnRoles);
        jPanel8.add(filler2);

        btnNuevoRol.setText("Nuevo Rol");
        btnNuevoRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoRolActionPerformed(evt);
            }
        });
        jPanel8.add(btnNuevoRol);
        jPanel8.add(filler7);

        btnActualizarRol.setText("Editar Rol");
        btnActualizarRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarRolActionPerformed(evt);
            }
        });
        jPanel8.add(btnActualizarRol);
        jPanel8.add(filler9);

        btnEliminarRol.setText("Eliminar Rol");
        btnEliminarRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarRolActionPerformed(evt);
            }
        });
        jPanel8.add(btnEliminarRol);
        jPanel8.add(filler6);

        pnlRolesPermisos.add(jPanel8, java.awt.BorderLayout.PAGE_START);

        jPanel16.setLayout(new java.awt.BorderLayout());

        tablePermisos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Accesos a gestion de", "Usuarios Creación", "Fecha de Creación"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePermisos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablePermisos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tablePermisosMouseReleased(evt);
            }
        });
        jScrollPane4.setViewportView(tablePermisos);
        if (tablePermisos.getColumnModel().getColumnCount() > 0) {
            tablePermisos.getColumnModel().getColumn(0).setMinWidth(320);
            tablePermisos.getColumnModel().getColumn(0).setPreferredWidth(320);
            tablePermisos.getColumnModel().getColumn(0).setMaxWidth(320);
        }

        jPanel16.add(jScrollPane4, java.awt.BorderLayout.PAGE_START);

        pnlRolesPermisos.add(jPanel16, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnNuevoPermiso.setText("Nuevo Permiso");
        btnNuevoPermiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoPermisoActionPerformed(evt);
            }
        });
        jPanel2.add(btnNuevoPermiso);

        btnEditarPermiso.setText("Editar Permiso");
        btnEditarPermiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPermisoActionPerformed(evt);
            }
        });
        jPanel2.add(btnEditarPermiso);

        btnEliminarPermiso.setText("Eliminar Permiso");
        btnEliminarPermiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPermisoActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminarPermiso);

        pnlRolesPermisos.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        tabRolesPantallas.addTab("ROLES - PERMISOS", pnlRolesPermisos);

        tablePantallas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdPantalla", "Nombre", "Descripción", "Recurso", "Fecha Creación"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePantallas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(tablePantallas);
        if (tablePantallas.getColumnModel().getColumnCount() > 0) {
            tablePantallas.getColumnModel().getColumn(0).setMinWidth(70);
            tablePantallas.getColumnModel().getColumn(0).setPreferredWidth(70);
            tablePantallas.getColumnModel().getColumn(0).setMaxWidth(70);
        }

        btnIngresar.setText("Nueva");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Editar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPantallasLayout = new javax.swing.GroupLayout(pnlPantallas);
        pnlPantallas.setLayout(pnlPantallasLayout);
        pnlPantallasLayout.setHorizontalGroup(
            pnlPantallasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPantallasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPantallasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
                    .addGroup(pnlPantallasLayout.createSequentialGroup()
                        .addComponent(btnIngresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlPantallasLayout.setVerticalGroup(
            pnlPantallasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPantallasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPantallasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresar)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar))
                .addGap(8, 8, 8)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabRolesPantallas.addTab("PANTALLAS", pnlPantallas);

        jPanel3.add(tabRolesPantallas, java.awt.BorderLayout.CENTER);
        tabRolesPantallas.getAccessibleContext().setAccessibleName("tab1");

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        setBounds(0, 0, 683, 458);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        new dlgSeguridadPantalla(JOptionPane.getFrameForComponent(this), true).setVisible(true);
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        dlgSeguridadPantalla dlgupdate = new dlgSeguridadPantalla(JOptionPane.getFrameForComponent(this), true);
        if (UtilTable.isAnyoneSelected(tablePantallas)) {
            Pantalla pantalla = pantallaBean.FindById(UtilTable.getSelectedOnColumn(tablePantallas, 0));
            dlgupdate.setTitle("Actualizar Pantalla");
            dlgupdate.setPantalla(pantalla);
            dlgupdate.setVisible(true);
        } else {
            Mensajes.SeleccioneFila(this);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void tablePermisosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePermisosMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tablePermisosMouseReleased

    private void cbnRolesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbnRolesItemStateChanged
        // TODO add your handling code here:
        LoadTablePermisos();
    }//GEN-LAST:event_cbnRolesItemStateChanged

    private void btnNuevoRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoRolActionPerformed
        // TODO add your handling code here:
        new dlgSeguridadRol(JOptionPane.getFrameForComponent(this), true).setVisible(true);
    }//GEN-LAST:event_btnNuevoRolActionPerformed

    private void btnActualizarRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarRolActionPerformed
        // TODO add your handling code here:
        dlgSeguridadRol dlgrol = new dlgSeguridadRol(JOptionPane.getFrameForComponent(this), true);
        dlgrol.setRol(roles.get(cbnRoles.getSelectedIndex()));
        dlgrol.setVisible(true);
    }//GEN-LAST:event_btnActualizarRolActionPerformed

    private void btnEliminarRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarRolActionPerformed

    private void btnNuevoPermisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoPermisoActionPerformed
        // TODO add your handling code here:
        Rol r = roles.get(cbnRoles.getSelectedIndex());
        if (pantallaBean.FindByRolNoPertenecen(r.getIdRol()).size() > 0) {
            dlgSeguridadPermiso dlgpermiso = new dlgSeguridadPermiso(JOptionPane.getFrameForComponent(this), true);
            dlgpermiso.setRol(r);
            dlgpermiso.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this,
                    "todas las pantallas ya tienen permisos en este rol",
                    "No hay registros disponibles",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnNuevoPermisoActionPerformed

    private void btnEditarPermisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPermisoActionPerformed
        // TODO add your handling code here:
        if (UtilTable.isAnyoneSelected(tablePermisos)) {
            Permiso permiso = permisos.get(tablePermisos.getSelectedRow());
            dlgSeguridadPermiso dlgpermiso = new dlgSeguridadPermiso(JOptionPane.getFrameForComponent(this), true);
            dlgpermiso.setPermiso(permiso);
            dlgpermiso.setVisible(true);
        } else {
            Mensajes.SeleccioneFila(this);
        }
    }//GEN-LAST:event_btnEditarPermisoActionPerformed

    private void btnEliminarPermisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPermisoActionPerformed
        // TODO add your handling code here:
        if (UtilTable.isAnyoneSelected(tablePermisos)) {
            int opc = Mensajes.Confirmacion(this, "Confirmar Eliminación", "¿Deseas Eliminar el Registro?");
            if (opc == JOptionPane.YES_OPTION) {
                Permiso permiso = permisos.get(tablePermisos.getSelectedRow());
                Dbcontext.eliminar(permiso);
                Mensajes.OperacionExitosa(this);
                LoadTablePermisos();
            }
        } else {
            Mensajes.SeleccioneFila(this);
        }
    }//GEN-LAST:event_btnEliminarPermisoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if (UtilTable.isAnyoneSelected(tablePantallas)) {
            int confirmar = Mensajes.Confirmacion(this, "Confirmar Eliminación", "¿Deseas Eliminar el Registro?");
            if (confirmar == JOptionPane.YES_OPTION) {
                Pantalla pantalla = pantallas.get(tablePantallas.getSelectedRow());
                Dbcontext.eliminar(pantalla);
                Mensajes.OperacionExitosa(this);
                LoadTablePantallas();
            }
        } else {
            Mensajes.SeleccioneFila(this);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnActualizarRol;
    private javax.swing.JButton btnEditarPermiso;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarPermiso;
    private javax.swing.JButton btnEliminarRol;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnNuevoPermiso;
    private javax.swing.JButton btnNuevoRol;
    private static javax.swing.JComboBox<String> cbnRoles;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPopupMenu pmPermisos;
    private javax.swing.JPanel pnlPantallas;
    private javax.swing.JPanel pnlRolesPermisos;
    private javax.swing.JTabbedPane tabRolesPantallas;
    private static javax.swing.JTable tablePantallas;
    private static javax.swing.JTable tablePermisos;
    // End of variables declaration//GEN-END:variables

    private void IniciarStatus() {
        new Thread(() -> {

        }).start();
    }

    private void LoadUI() {
        LoadComboRoles();
        LoadTablePermisos();
        LoadTablePantallas();
    }

    public synchronized static void LoadComboRoles() {
        roles = rolbean.FindAll();
        cbnRoles.removeAllItems();
        roles.stream().forEach((r) -> {
            cbnRoles.addItem(r.getRol());
        });
        cbnRoles.setSelectedIndex(0);
    }

    public synchronized static void LoadTablePermisos() {
        UtilTable.LimpiarTabla(tablePermisos);
        if (cbnRoles.getSelectedIndex() < 0) {
            permisos = permisoBean.FindByRol(roles.get(0).getIdRol());
        } else {
            permisos = permisoBean.FindByRol(roles.get(cbnRoles.getSelectedIndex()).getIdRol());
        }
        Object[] fila = new Object[4];
        permisos.stream().forEach((p) -> {
            fila[0] = pantallaBean.FindById(p.getId().getIdPantalla()).getNombre();
            fila[1] = p.getUsuarioByUserCreacion().getIdUsuario();
            fila[2] = UtilDate.DateFullNicaragua(p.getFechaCreacion());
            modelTablePermisos.addRow(fila);
        });
    }

    public static void LoadTablePantallas() {
        UtilTable.LimpiarTabla(tablePantallas);
        String[] filas = new String[5];
        pantallas = pantallaBean.FindAll();
        pantallas.stream().forEach((p) -> {
            filas[0] = p.getIdPantalla().toString();
            filas[1] = p.getNombre();
            filas[2] = p.getDescripcion();
            filas[3] = p.getRecurso();
            filas[4] = UtilDate.DateNicaraguaFecha(p.getFechaCreacion());
            modelTablePantallas.addRow(filas);
        });
    }
}
