/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dialogos;

import Conexion.Dbcontext;
import Conexion.SessionHelper;
import InternalFrames.ifrRegistroFacturas;
import POJOs.Agencia;
import POJOs.Cliente;
import POJOs.Factura;
import POJOs.Notadebito;
import POJOs.Producto;
import POJOs.Serviciosagencia;
import Utilidad.JTextValid;
import Utilidad.Mensajes;
import Utilidad.Validador;
import bean.ClienteBean;
import bean.FacturasBean;
import bean.ProductoBean;
import bean.AgenciaBean;
import bean.NotaDebitoBean;
import bean.ServicioAgenciaBean;
import java.awt.event.KeyEvent;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel-Zamora
 */
public class dlgFacturar extends javax.swing.JDialog {

    FacturasBean facturaBean;
    static ClienteBean clientesBean = new ClienteBean();
    static ProductoBean productoBean = new ProductoBean();
    static AgenciaBean agenciaBean = new AgenciaBean();
    ServicioAgenciaBean servicioAgenciaBean = new ServicioAgenciaBean();

    Factura factura;
    private final int CantidadCaracteres = 130;
    static List<Cliente> clientes;
    static List<Producto> productos;
    static List<Agencia> agencias;

    public static boolean OperationType = true; //True Guardar; False Modificar
    public static boolean FacturarActiva = false;

    public dlgFacturar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.OperationType = true;
        Cargas(OperationType);
        CargarConsecutivo();
        btnModificar.setVisible(false);
        FacturarActiva = true;
        ActivarValidator();
    }

    public dlgFacturar(java.awt.Frame parent, boolean modal, int CuentaRegistro) {
        super(parent, modal);
        initComponents();
        this.OperationType = false;
        Cargas(OperationType);
        CargarInformacion(CuentaRegistro);
        btnGuardar.setVisible(false);
        FacturarActiva = true;
        ActivarValidator();
        BloquearCampos(VerficarNotasImpresas());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        lblCaracteres = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCuentaRegistro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cboClientes = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        cboProductos = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        rbExportacion = new javax.swing.JRadioButton();
        rbImportacion = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        txtDeclaracion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rbTerrestre = new javax.swing.JRadioButton();
        rbMaritima = new javax.swing.JRadioButton();
        rbAerea = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        txtRemitido = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtFacturaNo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtValorCIF = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtHonorarios = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtManejo = new javax.swing.JTextField();
        txtValorizacion = new javax.swing.JTextField();
        txtPartidasAdicionales = new javax.swing.JTextField();
        chkIVA = new javax.swing.JCheckBox();
        btnAddProducto = new javax.swing.JButton();
        btnAddCliente = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cboAgencia = new javax.swing.JComboBox<>();
        btnAddAduana = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Facturación");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("<html><Strong>FACTURACIÓN");
        jPanel1.add(jLabel7);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel17.setText("Caracteres de Descripción Restantes:");
        jPanel5.add(jLabel17);

        lblCaracteres.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCaracteres.setText("130");
        jPanel5.add(lblCaracteres);

        jPanel2.add(jPanel5);

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel6.add(btnGuardar);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel6.add(btnModificar);

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1);

        jPanel2.add(jPanel6);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("CUENTA DE REGISTRO NO.");

        txtCuentaRegistro.setEditable(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Cliente:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Descripción:");

        txtDescripcion.setColumns(20);
        txtDescripcion.setLineWrap(true);
        txtDescripcion.setRows(5);
        txtDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDescripcionKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDescripcionKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescripcionKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtDescripcion);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Tipo de Transacción:");

        buttonGroup1.add(rbExportacion);
        rbExportacion.setSelected(true);
        rbExportacion.setText("Exportación");

        buttonGroup1.add(rbImportacion);
        rbImportacion.setText("Importación");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("NUMERO DE DECLARACIÓN:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Tipo de llegada:");

        buttonGroup2.add(rbTerrestre);
        rbTerrestre.setSelected(true);
        rbTerrestre.setText("Terrestre");

        buttonGroup2.add(rbMaritima);
        rbMaritima.setText("Marítima");

        buttonGroup2.add(rbAerea);
        rbAerea.setText("Aérea");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Remitido Por:");

        txtRemitido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRemitidoActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Factura No.");

        txtFacturaNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFacturaNoActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Valor CIF:");

        txtValorCIF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorCIFActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("<html><strong>Servicios de Agencia Aduanera"));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Honorarios:");

        txtHonorarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHonorariosActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Manejo:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Valorización:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Partidas Adicionales:");

        txtManejo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManejoActionPerformed(evt);
            }
        });

        txtValorizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorizacionActionPerformed(evt);
            }
        });

        txtPartidasAdicionales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPartidasAdicionalesActionPerformed(evt);
            }
        });

        chkIVA.setSelected(true);
        chkIVA.setText("Se le aplica IVA");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHonorarios)
                            .addComponent(txtManejo)
                            .addComponent(txtValorizacion)
                            .addComponent(txtPartidasAdicionales)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(chkIVA)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtHonorarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtManejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtValorizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtPartidasAdicionales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkIVA))
        );

        btnAddProducto.setText("+");
        btnAddProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductoActionPerformed(evt);
            }
        });

        btnAddCliente.setText("+");
        btnAddCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddClienteActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Producto Asociado:");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Aduana:");

        btnAddAduana.setText("+");
        btnAddAduana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAduanaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(cboClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCuentaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtValorCIF, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtFacturaNo, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtRemitido, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(39, 39, 39)
                                        .addComponent(cboAgencia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnAddAduana, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbTerrestre)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbMaritima)))
                                .addGap(6, 6, 6)
                                .addComponent(rbAerea)))
                        .addGap(14, 14, 14)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(22, 22, 22)
                                .addComponent(txtDeclaracion, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(rbExportacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbImportacion)
                                .addGap(16, 16, 16)))
                        .addComponent(btnAddProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCuentaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnAddCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDeclaracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(btnAddProducto)
                            .addComponent(jLabel16))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(rbExportacion)
                            .addComponent(rbImportacion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(rbTerrestre)
                            .addComponent(rbMaritima)
                            .addComponent(rbAerea))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(cboAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddAduana))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtRemitido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtFacturaNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtValorCIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(854, 454));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void btnAddClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddClienteActionPerformed
        new dlgClientes(new javax.swing.JFrame(), true).setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddClienteActionPerformed

    private void btnAddProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductoActionPerformed
        new dlgProductos(JOptionPane.getFrameForComponent(this), true).setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddProductoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (ValidarCampos()) {
            Mensajes.InformacionIncompleta(this);
            return;
        }
        if (VerificarServiciosAgenciaAduanera()) {
            try {
                int Decision = JOptionPane.showConfirmDialog(this, "Esta a punto de Guardar una Factura sin cargos por Servicio de Agencia Aduanera, ¿realmente desea guardar esta Factura?", "Advertencia", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (Decision == 0) {
                    if (Guardar()) {
                        Mensajes.OperacionExitosa(this);
                        LimpiarCampos();
                        CargarTablaRegistroFacturas("");
                    }
                }
            } catch (NumberFormatException e) {
            }

        } else {
            int DecisionFinal = JOptionPane.showConfirmDialog(this, Utilidad.Mensajes.CONFIRMA_INSERSION, "Mensaje de Confirmacion", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (DecisionFinal == 0) {
                if (Guardar()) {
                    Mensajes.OperacionExitosa(this);
                    LimpiarCampos();
                    CargarTablaRegistroFacturas("");
                }
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnAddAduanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAduanaActionPerformed
        new dlgAgencia(JOptionPane.getFrameForComponent(this), true).setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddAduanaActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if (ValidarCampos()) {
            Mensajes.InformacionIncompleta(this);
            return;
        }
        if (VerificarServiciosAgenciaAduanera()) {
            try {
                int Decision = JOptionPane.showConfirmDialog(this, "Esta a punto de Modificar una Factura sin cargos por Servicio de Agencia Aduanera, ¿realmente desea Guardar la Factura de esta manera?", "Advertencia", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (Decision == 0) {
                    int DecisionFinal = JOptionPane.showConfirmDialog(this, Utilidad.Mensajes.CONFIRMA_ACTUALIZACION, "Mensaje de Confirmacion", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                    if (DecisionFinal == 0) {
                        if (Mofificar()) {
                            Mensajes.OperacionExitosa(this);
                            CargarTablaRegistroFacturas("Modifica");
                            dispose();
//                            LimpiarCampos();
                        }
                    }

                }
            } catch (NumberFormatException e) {
            }

        } else {
            int DecisionFinal = JOptionPane.showConfirmDialog(this, Utilidad.Mensajes.CONFIRMA_ACTUALIZACION, "Mensaje de Confirmacion", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (DecisionFinal == 0) {
                if (Mofificar()) {
                    Mensajes.OperacionExitosa(this);
                    CargarTablaRegistroFacturas("Modifica");
                    dispose();
//                    LimpiarCampos();
                }
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarActionPerformed

    private void txtFacturaNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFacturaNoActionPerformed
        JTextValid.EnviarFoco(txtFacturaNo, txtValorCIF);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFacturaNoActionPerformed

    private void txtRemitidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRemitidoActionPerformed
        JTextValid.EnviarFoco(txtRemitido, txtFacturaNo);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRemitidoActionPerformed

    private void txtValorCIFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorCIFActionPerformed
        JTextValid.EnviarFoco(txtValorCIF, txtHonorarios);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorCIFActionPerformed

    private void txtManejoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManejoActionPerformed
        JTextValid.EnviarFoco(txtManejo, txtValorizacion);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManejoActionPerformed

    private void txtValorizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorizacionActionPerformed
        JTextValid.EnviarFoco(txtValorizacion, txtPartidasAdicionales);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorizacionActionPerformed

    private void txtPartidasAdicionalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPartidasAdicionalesActionPerformed
        JTextValid.EnviarFoco(txtPartidasAdicionales, btnGuardar);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPartidasAdicionalesActionPerformed

    private void txtHonorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHonorariosActionPerformed
        JTextValid.EnviarFoco(txtHonorarios, txtManejo);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHonorariosActionPerformed

    private void txtDescripcionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcionKeyPressed
        char c = evt.getKeyChar();
        if (c == KeyEvent.VK_ENTER || c == KeyEvent.VK_TAB) {
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionKeyPressed

    private void txtDescripcionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcionKeyReleased
        lblCaracteres.setText("" + CantidadRestante());
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionKeyReleased

    private void txtDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcionKeyTyped
        if (txtDescripcion.getText().length() >= CantidadCaracteres) {
            lblCaracteres.setText("" + CantidadRestante());
            evt.consume();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dlgFacturar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dlgFacturar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dlgFacturar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dlgFacturar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            dlgFacturar dialog = new dlgFacturar(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAduana;
    private javax.swing.JButton btnAddCliente;
    private javax.swing.JButton btnAddProducto;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private static javax.swing.JComboBox<String> cboAgencia;
    private static javax.swing.JComboBox<String> cboClientes;
    private static javax.swing.JComboBox<String> cboProductos;
    private javax.swing.JCheckBox chkIVA;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCaracteres;
    private javax.swing.JRadioButton rbAerea;
    private javax.swing.JRadioButton rbExportacion;
    private javax.swing.JRadioButton rbImportacion;
    private javax.swing.JRadioButton rbMaritima;
    private javax.swing.JRadioButton rbTerrestre;
    private javax.swing.JTextField txtCuentaRegistro;
    private javax.swing.JTextField txtDeclaracion;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtFacturaNo;
    private javax.swing.JTextField txtHonorarios;
    private javax.swing.JTextField txtManejo;
    private javax.swing.JTextField txtPartidasAdicionales;
    private javax.swing.JTextField txtRemitido;
    private javax.swing.JTextField txtValorCIF;
    private javax.swing.JTextField txtValorizacion;
    // End of variables declaration//GEN-END:variables

    private void CargarConsecutivo() {
        facturaBean = new FacturasBean();
        try {
            txtCuentaRegistro.setText("" + facturaBean.FacturaConsecutiva());
        } catch (NullPointerException e) {
            txtCuentaRegistro.setText("1");
        }
    }

    public static void CargarClientes(boolean ObjetivoCarga) {
        cboClientes.removeAllItems();
        clientes = clientesBean.FindAll(ObjetivoCarga);
        for (Cliente cliente : clientes) {
            cboClientes.addItem(cliente.getRazonSocial());
        }
    }

    public static void CargarProductos(boolean ObjetivoCarga) {
        cboProductos.removeAllItems();
        productos = productoBean.FindAll(ObjetivoCarga);
        for (Producto producto : productos) {
            cboProductos.addItem(producto.getNombre().toUpperCase());
        }
    }

    public static void CargarAgencias(boolean ObjetivoCarga) {
        cboAgencia.removeAllItems();
        agencias = agenciaBean.FindAll(ObjetivoCarga);
        agencias.stream().forEach((agencia) -> {
            cboAgencia.addItem(agencia.getNombre().toUpperCase());
        });

    }

    private boolean ValidarCampos() {
        boolean vacio = false;
        if (txtDescripcion.getText().equals("") || txtDeclaracion.getText().equals("")
                || txtRemitido.getText().equals("") || txtFacturaNo.getText().equals("")
                || txtValorCIF.getText().equals("")) {
            vacio = true;
        }
        return vacio;
    }

    private boolean VerificarServiciosAgenciaAduanera() {
        boolean sinServicios = false;
        if (txtHonorarios.getText().equals("") && txtManejo.getText().equals("")
                && txtValorizacion.getText().equals("")
                && txtPartidasAdicionales.getText().equals("")) {
            sinServicios = true;
        }
        return sinServicios;
    }

    private boolean Guardar() {
        boolean Guardo;
        facturaBean = new FacturasBean();
        Factura f = new Factura();
        try {
            f.setCuentaRegistro(facturaBean.FacturaConsecutiva());
        } catch (NullPointerException e) {
            f.setCuentaRegistro(1);
            Mensajes.ErrorMessage(this, "Error a nivel de Obtencion Numero Consecutivo", e.getMessage());
        }

        f.setCliente(clientes.get(cboClientes.getSelectedIndex()));
        f.setDescripcion(txtDescripcion.getText());
        f.setProducto(productos.get(cboProductos.getSelectedIndex()));
        f.setAgencia(agencias.get(cboAgencia.getSelectedIndex()));
        f.setTipoTransaccion((rbImportacion.isSelected()));
        f.setNumeroDeclaracion(txtDeclaracion.getText());
        f.setTipoLlegada((rbTerrestre.isSelected() ? "1" : (rbMaritima.isSelected() ? "2" : "3")));
        f.setRemite(txtRemitido.getText());
        f.setFacturaExterna(txtFacturaNo.getText());
        f.setValorCif(Double.parseDouble(txtValorCIF.getText()));
        f.setUsuarioByUserCreacion(SessionHelper.usuario);
        f.setFechaCreacion(new Date());
        f.setUsuarioByUserModificacion(SessionHelper.usuario);
        f.setFechaModificacion(new Date());
        f.setEstado("Generada");

        Serviciosagencia sa = new Serviciosagencia();
        sa.setFactura(f);
        sa.setCuentaRegistro(f.getCuentaRegistro());
        sa.setHonorario(Double.parseDouble((txtHonorarios.getText().equals("")) ? "0.00" : txtHonorarios.getText()));
        sa.setManejo(Double.parseDouble((txtManejo.getText().equals("")) ? "0.00" : txtManejo.getText()));
        sa.setValorizacion(Double.parseDouble((txtValorizacion.getText().equals("")) ? "0.00" : txtValorizacion.getText()));
        sa.setPartidasAdicionales(Double.parseDouble((txtPartidasAdicionales.getText().equals("")) ? "0.00" : txtPartidasAdicionales.getText()));
        sa.setAplicaIva(chkIVA.isSelected());

        try {
            Dbcontext.guardar(f);
            if (!txtCuentaRegistro.getText().equals("" + f.getCuentaRegistro())) {
                Mensajes.InfoMessage(this, "Cambio en el Número de Cuenta de Registro", "Se detectó un cambio en el número principal de la cuenta de registro ->" + txtCuentaRegistro.getText()
                        + ", por lo tanto la factura se guardó con el número de Cuenta ->" + f.getCuentaRegistro());
            }
            Dbcontext.guardar(sa);
            Guardo = true;
        } catch (Exception e) {
            Guardo = false;
            Mensajes.ErrorDesconocido(this, e.getMessage());
            e.printStackTrace();
        }
        return Guardo;
    }

    private boolean Mofificar() {
        boolean modifico = false;
        Factura f = factura;
        f.setCuentaRegistro(Integer.parseInt(txtCuentaRegistro.getText()));
        f.setCliente(clientes.get(cboClientes.getSelectedIndex()));
        f.setDescripcion(txtDescripcion.getText());
        f.setProducto(productos.get(cboProductos.getSelectedIndex()));
        f.setAgencia(agencias.get(cboAgencia.getSelectedIndex()));
        f.setTipoTransaccion((rbImportacion.isSelected()));
        f.setNumeroDeclaracion(txtDeclaracion.getText());
        f.setTipoLlegada((rbTerrestre.isSelected() ? "1" : (rbMaritima.isSelected() ? "2" : "3")));
        f.setRemite(txtRemitido.getText());
        f.setFacturaExterna(txtFacturaNo.getText());
        f.setValorCif(Double.parseDouble(txtValorCIF.getText()));
        f.setUsuarioByUserCreacion(factura.getUsuarioByUserCreacion());
        f.setUsuarioByUserModificacion(SessionHelper.usuario);
        f.setEstado("Modificada");
        f.setFechaCreacion(factura.getFechaCreacion());
        f.setFechaModificacion(new Date());

        Serviciosagencia sa = new Serviciosagencia();
        sa.setCuentaRegistro(Integer.parseInt(txtCuentaRegistro.getText()));
        sa.setHonorario(Double.parseDouble((txtHonorarios.getText().equals("")) ? "0.00" : txtHonorarios.getText()));
        sa.setManejo(Double.parseDouble((txtManejo.getText().equals("")) ? "0.00" : txtManejo.getText()));
        sa.setValorizacion(Double.parseDouble((txtValorizacion.getText().equals("")) ? "0.00" : txtValorizacion.getText()));
        sa.setPartidasAdicionales(Double.parseDouble((txtPartidasAdicionales.getText().equals("")) ? "0.00" : txtPartidasAdicionales.getText()));
        sa.setAplicaIva(chkIVA.isSelected());

        try {
            Dbcontext.actualizar(f);
            Dbcontext.guardarOrActualizar(sa);
            modifico = true;
        } catch (Exception e) {
            modifico = false;
            Mensajes.ErrorDesconocido(this, e.getMessage());
        }
        return modifico;
    }

    private void LimpiarCampos() {
        txtDescripcion.setText("");
        txtDeclaracion.setText("");
        txtRemitido.setText("");
        txtFacturaNo.setText("");
        txtValorCIF.setText("");
        txtHonorarios.setText("");
        txtManejo.setText("");
        txtValorizacion.setText("");
        txtPartidasAdicionales.setText("");
        CargarConsecutivo();
    }

    private void CargarInformacion(int CuentaRegistro) {
        facturaBean = new FacturasBean();
        factura = facturaBean.FindById(CuentaRegistro);
        Serviciosagencia sa = servicioAgenciaBean.FindById(CuentaRegistro);
        Cliente cliente = clientesBean.FindById(factura.getCliente().getIdCliente());
        Agencia agencia = agenciaBean.FindById(factura.getAgencia().getIdAgencia());
        Producto producto = productoBean.FindById(factura.getProducto().getIdProducto());
        txtCuentaRegistro.setText("" + factura.getCuentaRegistro());

        if (cliente.getRegAnulado()) { //Si el cliente esta anulado no permito editarlo
            cboClientes.setEnabled(false);
            btnAddCliente.setEnabled(false);
        }
        cboClientes.setSelectedItem(cliente.getRazonSocial());

        if (agencia.getRegAnulado()) { // Si la agencia esta anulada no permito editarla
            cboAgencia.setEnabled(false);
            btnAddAduana.setEnabled(false);
        }
        cboAgencia.setSelectedItem(agencia.getNombre().toUpperCase());

        if (producto.getRegAnulado()) { // Si el producto esta anulado no permito editarlo
            cboProductos.setEnabled(false);
            btnAddProducto.setEnabled(false);
        }
        cboProductos.setSelectedItem(producto.getNombre().toUpperCase());

        txtDescripcion.setText(factura.getDescripcion());

        lblCaracteres.setText("" + CantidadRestante());

        txtDeclaracion.setText(factura.getNumeroDeclaracion());
        if (factura.getTipoTransaccion()) {
            rbImportacion.setSelected(true);
        } else {
            rbExportacion.setSelected(true);
        }

        if (factura.getTipoLlegada().equals("1")) {
            rbTerrestre.setSelected(true);
        } else if (factura.getTipoLlegada().equals("2")) {
            rbMaritima.setSelected(true);
        } else {
            rbAerea.setSelected(true);
        }
        txtRemitido.setText(factura.getRemite());
        txtFacturaNo.setText(factura.getFacturaExterna());
        txtValorCIF.setText("" + factura.getValorCif());
        if (sa != null) {
            txtManejo.setText("" + sa.getManejo());
            txtValorizacion.setText("" + sa.getValorizacion());
            txtHonorarios.setText("" + sa.getHonorario());
            txtPartidasAdicionales.setText("" + sa.getPartidasAdicionales());
            chkIVA.setSelected(sa.getAplicaIva());
        }
    }

    private void Cargas(boolean ObjetivoCarga) {
        CargarClientes(ObjetivoCarga);
        CargarProductos(ObjetivoCarga);
        CargarAgencias(ObjetivoCarga);
    }

    private void CargarTablaRegistroFacturas(String TipoGestion) {
        //Si el tipo de gestion es Modifica entonces que se cargue solo la tabla y no el combo
        if (ifrRegistroFacturas.RegistroFacturasActiva) {
            if (TipoGestion.equals("")) {
                ifrRegistroFacturas.FirstRun = true;
                ifrRegistroFacturas.CargarTabla();
            } else {
                ifrRegistroFacturas.CargarTabla();
            }
        }
    }

    private void ActivarValidator() {
        Validador.Validar(txtDeclaracion, Validador.ALFANUMERICO_WITH_SPACE);
        Validador.Validar(txtRemitido, Validador.ALFANUMERICO_WITH_SPACE);
        Validador.Validar(txtFacturaNo, Validador.ALFANUMERICO_WITH_SPACE);
        Validador.Validar(txtValorCIF, Validador.NUMEROS);
        Validador.Validar(txtHonorarios, Validador.NUMEROS);
        Validador.Validar(txtManejo, Validador.NUMEROS);
        Validador.Validar(txtValorizacion, Validador.NUMEROS);
        Validador.Validar(txtPartidasAdicionales, Validador.NUMEROS);
    }

    private void BloquearCampos(boolean flag) {
        cboClientes.setEnabled(flag);
        btnAddCliente.setVisible(flag);
        cboAgencia.setEnabled(flag);
        btnAddAduana.setVisible(flag);
        cboProductos.setEnabled(flag);
        btnAddProducto.setVisible(flag);
        rbExportacion.setEnabled(flag);
        rbImportacion.setEnabled(flag);
        txtDeclaracion.setEnabled(flag);

    }

    private boolean VerficarNotasImpresas() {
        boolean NoImprimio = true;
        NotaDebitoBean notaDebitoBean = new NotaDebitoBean();
        for (Notadebito nd : notaDebitoBean.FindAll(factura.getCuentaRegistro())) {
            if (nd.getEstado().equals("Impresa") || nd.getEstado().equals("Pagada")) {
                NoImprimio = false;
                break;
            }
        }
        return NoImprimio;
    }

    private int CantidadRestante() {
        return (CantidadCaracteres - txtDescripcion.getText().length());
    }
}
