package POJOs;
// Generated 06-08-2018 02:18:23 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer idCliente;
     private Usuario usuarioByUserCreacion;
     private Usuario usuarioByUserModificacion;
     private String razonSocial;
     private String ruc;
     private String telefono;
     private String correo;
     private String direccion;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private Boolean regAnulado;
     private Set recibos = new HashSet(0);
     private Set notadebitos = new HashSet(0);
     private Set facturas = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(Usuario usuarioByUserCreacion, String razonSocial, String ruc, String direccion) {
        this.usuarioByUserCreacion = usuarioByUserCreacion;
        this.razonSocial = razonSocial;
        this.ruc = ruc;
        this.direccion = direccion;
    }
    public Cliente(Usuario usuarioByUserCreacion, Usuario usuarioByUserModificacion, String razonSocial, String ruc, String telefono, String correo, String direccion, Date fechaCreacion, Date fechaModificacion, Boolean regAnulado, Set recibos, Set notadebitos, Set facturas) {
       this.usuarioByUserCreacion = usuarioByUserCreacion;
       this.usuarioByUserModificacion = usuarioByUserModificacion;
       this.razonSocial = razonSocial;
       this.ruc = ruc;
       this.telefono = telefono;
       this.correo = correo;
       this.direccion = direccion;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.regAnulado = regAnulado;
       this.recibos = recibos;
       this.notadebitos = notadebitos;
       this.facturas = facturas;
    }
   
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
    public Usuario getUsuarioByUserCreacion() {
        return this.usuarioByUserCreacion;
    }
    
    public void setUsuarioByUserCreacion(Usuario usuarioByUserCreacion) {
        this.usuarioByUserCreacion = usuarioByUserCreacion;
    }
    public Usuario getUsuarioByUserModificacion() {
        return this.usuarioByUserModificacion;
    }
    
    public void setUsuarioByUserModificacion(Usuario usuarioByUserModificacion) {
        this.usuarioByUserModificacion = usuarioByUserModificacion;
    }
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }
    public String getRuc() {
        return this.ruc;
    }
    
    public void setRuc(String ruc) {
        this.ruc = ruc;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Boolean getRegAnulado() {
        return this.regAnulado;
    }
    
    public void setRegAnulado(Boolean regAnulado) {
        this.regAnulado = regAnulado;
    }
    public Set getRecibos() {
        return this.recibos;
    }
    
    public void setRecibos(Set recibos) {
        this.recibos = recibos;
    }
    public Set getNotadebitos() {
        return this.notadebitos;
    }
    
    public void setNotadebitos(Set notadebitos) {
        this.notadebitos = notadebitos;
    }
    public Set getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set facturas) {
        this.facturas = facturas;
    }




}


