package POJOs;
// Generated 06-08-2018 02:18:23 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Detallerecibo generated by hbm2java
 */
public class Detallerecibo  implements java.io.Serializable {


     private Integer idDetalleRecibo;
     private Factura factura;
     private Notadebito notadebito;
     private Recibo recibo;
     private double monto;
     private String userCreacion;
     private Date fechaCreacion;
     private String userModificacion;
     private Date fechaModificacion;

    public Detallerecibo() {
    }

	
    public Detallerecibo(Recibo recibo, double monto) {
        this.recibo = recibo;
        this.monto = monto;
    }
    public Detallerecibo(Factura factura, Notadebito notadebito, Recibo recibo, double monto, String userCreacion, Date fechaCreacion, String userModificacion, Date fechaModificacion) {
       this.factura = factura;
       this.notadebito = notadebito;
       this.recibo = recibo;
       this.monto = monto;
       this.userCreacion = userCreacion;
       this.fechaCreacion = fechaCreacion;
       this.userModificacion = userModificacion;
       this.fechaModificacion = fechaModificacion;
    }
   
    public Integer getIdDetalleRecibo() {
        return this.idDetalleRecibo;
    }
    
    public void setIdDetalleRecibo(Integer idDetalleRecibo) {
        this.idDetalleRecibo = idDetalleRecibo;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    public Notadebito getNotadebito() {
        return this.notadebito;
    }
    
    public void setNotadebito(Notadebito notadebito) {
        this.notadebito = notadebito;
    }
    public Recibo getRecibo() {
        return this.recibo;
    }
    
    public void setRecibo(Recibo recibo) {
        this.recibo = recibo;
    }
    public double getMonto() {
        return this.monto;
    }
    
    public void setMonto(double monto) {
        this.monto = monto;
    }
    public String getUserCreacion() {
        return this.userCreacion;
    }
    
    public void setUserCreacion(String userCreacion) {
        this.userCreacion = userCreacion;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getUserModificacion() {
        return this.userModificacion;
    }
    
    public void setUserModificacion(String userModificacion) {
        this.userModificacion = userModificacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }




}


