package POJOs;
// Generated 06-08-2018 02:18:23 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Detallenotadebito generated by hbm2java
 */
public class Detallenotadebito  implements java.io.Serializable {


     private Integer idDetalleNotaDebito;
     private Notadebito notadebito;
     private Usuario usuarioByUserCreacion;
     private Usuario usuarioByUserModificacion;
     private String detalle;
     private double monto;
     private Date fechaCreacion;
     private Date fechaModificacion;

    public Detallenotadebito() {
    }

	
    public Detallenotadebito(Notadebito notadebito, Usuario usuarioByUserCreacion, String detalle, double monto) {
        this.notadebito = notadebito;
        this.usuarioByUserCreacion = usuarioByUserCreacion;
        this.detalle = detalle;
        this.monto = monto;
    }
    public Detallenotadebito(Notadebito notadebito, Usuario usuarioByUserCreacion, Usuario usuarioByUserModificacion, String detalle, double monto, Date fechaCreacion, Date fechaModificacion) {
       this.notadebito = notadebito;
       this.usuarioByUserCreacion = usuarioByUserCreacion;
       this.usuarioByUserModificacion = usuarioByUserModificacion;
       this.detalle = detalle;
       this.monto = monto;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
    }
   
    public Integer getIdDetalleNotaDebito() {
        return this.idDetalleNotaDebito;
    }
    
    public void setIdDetalleNotaDebito(Integer idDetalleNotaDebito) {
        this.idDetalleNotaDebito = idDetalleNotaDebito;
    }
    public Notadebito getNotadebito() {
        return this.notadebito;
    }
    
    public void setNotadebito(Notadebito notadebito) {
        this.notadebito = notadebito;
    }
    public Usuario getUsuarioByUserCreacion() {
        return this.usuarioByUserCreacion;
    }
    
    public void setUsuarioByUserCreacion(Usuario usuarioByUserCreacion) {
        this.usuarioByUserCreacion = usuarioByUserCreacion;
    }
    public Usuario getUsuarioByUserModificacion() {
        return this.usuarioByUserModificacion;
    }
    
    public void setUsuarioByUserModificacion(Usuario usuarioByUserModificacion) {
        this.usuarioByUserModificacion = usuarioByUserModificacion;
    }
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }
    public double getMonto() {
        return this.monto;
    }
    
    public void setMonto(double monto) {
        this.monto = monto;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }




}


