package POJOs;
// Generated 06-08-2018 02:18:23 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private int idEmpleado;
     private Persona persona;
     private Usuario usuarioByUserModificacion;
     private Usuario usuarioByUserCreacion;
     private String cargo;
     private double salario;
     private Date fechaInicio;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private Boolean regAnulado;
     private Set usuarios = new HashSet(0);

    public Empleado() {
    }

	
    public Empleado(Persona persona, String cargo, double salario, Date fechaInicio) {
        this.persona = persona;
        this.cargo = cargo;
        this.salario = salario;
        this.fechaInicio = fechaInicio;
    }
    public Empleado(Persona persona, Usuario usuarioByUserModificacion, Usuario usuarioByUserCreacion, String cargo, double salario, Date fechaInicio, Date fechaCreacion, Date fechaModificacion, Boolean regAnulado, Set usuarios) {
       this.persona = persona;
       this.usuarioByUserModificacion = usuarioByUserModificacion;
       this.usuarioByUserCreacion = usuarioByUserCreacion;
       this.cargo = cargo;
       this.salario = salario;
       this.fechaInicio = fechaInicio;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.regAnulado = regAnulado;
       this.usuarios = usuarios;
    }
   
    public int getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(int idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Usuario getUsuarioByUserModificacion() {
        return this.usuarioByUserModificacion;
    }
    
    public void setUsuarioByUserModificacion(Usuario usuarioByUserModificacion) {
        this.usuarioByUserModificacion = usuarioByUserModificacion;
    }
    public Usuario getUsuarioByUserCreacion() {
        return this.usuarioByUserCreacion;
    }
    
    public void setUsuarioByUserCreacion(Usuario usuarioByUserCreacion) {
        this.usuarioByUserCreacion = usuarioByUserCreacion;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public double getSalario() {
        return this.salario;
    }
    
    public void setSalario(double salario) {
        this.salario = salario;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Boolean getRegAnulado() {
        return this.regAnulado;
    }
    
    public void setRegAnulado(Boolean regAnulado) {
        this.regAnulado = regAnulado;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


