package POJOs;
// Generated 06-08-2018 02:18:23 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Notadebito generated by hbm2java
 */
public class Notadebito  implements java.io.Serializable {


     private int notaDebito;
     private Cliente cliente;
     private Factura factura;
     private Usuario usuarioByUserImpresion;
     private Usuario usuarioByUserCreacion;
     private Usuario usuarioByUserModificacion;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private String estado;
     private Date fechaImpresion;
     private Set detallenotadebitos = new HashSet(0);
     private Set detallerecibos = new HashSet(0);

    public Notadebito() {
    }

	
    public Notadebito(int notaDebito, Usuario usuarioByUserCreacion) {
        this.notaDebito = notaDebito;
        this.usuarioByUserCreacion = usuarioByUserCreacion;
    }
    public Notadebito(int notaDebito, Cliente cliente, Factura factura, Usuario usuarioByUserImpresion, Usuario usuarioByUserCreacion, Usuario usuarioByUserModificacion, Date fechaCreacion, Date fechaModificacion, String estado, Date fechaImpresion, Set detallenotadebitos, Set detallerecibos) {
       this.notaDebito = notaDebito;
       this.cliente = cliente;
       this.factura = factura;
       this.usuarioByUserImpresion = usuarioByUserImpresion;
       this.usuarioByUserCreacion = usuarioByUserCreacion;
       this.usuarioByUserModificacion = usuarioByUserModificacion;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.estado = estado;
       this.fechaImpresion = fechaImpresion;
       this.detallenotadebitos = detallenotadebitos;
       this.detallerecibos = detallerecibos;
    }
   
    public int getNotaDebito() {
        return this.notaDebito;
    }
    
    public void setNotaDebito(int notaDebito) {
        this.notaDebito = notaDebito;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    public Usuario getUsuarioByUserImpresion() {
        return this.usuarioByUserImpresion;
    }
    
    public void setUsuarioByUserImpresion(Usuario usuarioByUserImpresion) {
        this.usuarioByUserImpresion = usuarioByUserImpresion;
    }
    public Usuario getUsuarioByUserCreacion() {
        return this.usuarioByUserCreacion;
    }
    
    public void setUsuarioByUserCreacion(Usuario usuarioByUserCreacion) {
        this.usuarioByUserCreacion = usuarioByUserCreacion;
    }
    public Usuario getUsuarioByUserModificacion() {
        return this.usuarioByUserModificacion;
    }
    
    public void setUsuarioByUserModificacion(Usuario usuarioByUserModificacion) {
        this.usuarioByUserModificacion = usuarioByUserModificacion;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Date getFechaImpresion() {
        return this.fechaImpresion;
    }
    
    public void setFechaImpresion(Date fechaImpresion) {
        this.fechaImpresion = fechaImpresion;
    }
    public Set getDetallenotadebitos() {
        return this.detallenotadebitos;
    }
    
    public void setDetallenotadebitos(Set detallenotadebitos) {
        this.detallenotadebitos = detallenotadebitos;
    }
    public Set getDetallerecibos() {
        return this.detallerecibos;
    }
    
    public void setDetallerecibos(Set detallerecibos) {
        this.detallerecibos = detallerecibos;
    }




}


