package POJOs;
// Generated 06-08-2018 02:18:23 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pantalla generated by hbm2java
 */
public class Pantalla  implements java.io.Serializable {


     private Integer idPantalla;
     private Usuario usuarioByUserModificacion;
     private Usuario usuarioByUserCreacion;
     private String nombre;
     private String recurso;
     private String descripcion;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private Boolean regAnulado;
     private Set permisos = new HashSet(0);

    public Pantalla() {
    }

	
    public Pantalla(Usuario usuarioByUserCreacion, String recurso) {
        this.usuarioByUserCreacion = usuarioByUserCreacion;
        this.recurso = recurso;
    }
    public Pantalla(Usuario usuarioByUserModificacion, Usuario usuarioByUserCreacion, String nombre, String recurso, String descripcion, Date fechaCreacion, Date fechaModificacion, Boolean regAnulado, Set permisos) {
       this.usuarioByUserModificacion = usuarioByUserModificacion;
       this.usuarioByUserCreacion = usuarioByUserCreacion;
       this.nombre = nombre;
       this.recurso = recurso;
       this.descripcion = descripcion;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.regAnulado = regAnulado;
       this.permisos = permisos;
    }
   
    public Integer getIdPantalla() {
        return this.idPantalla;
    }
    
    public void setIdPantalla(Integer idPantalla) {
        this.idPantalla = idPantalla;
    }
    public Usuario getUsuarioByUserModificacion() {
        return this.usuarioByUserModificacion;
    }
    
    public void setUsuarioByUserModificacion(Usuario usuarioByUserModificacion) {
        this.usuarioByUserModificacion = usuarioByUserModificacion;
    }
    public Usuario getUsuarioByUserCreacion() {
        return this.usuarioByUserCreacion;
    }
    
    public void setUsuarioByUserCreacion(Usuario usuarioByUserCreacion) {
        this.usuarioByUserCreacion = usuarioByUserCreacion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getRecurso() {
        return this.recurso;
    }
    
    public void setRecurso(String recurso) {
        this.recurso = recurso;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Boolean getRegAnulado() {
        return this.regAnulado;
    }
    
    public void setRegAnulado(Boolean regAnulado) {
        this.regAnulado = regAnulado;
    }
    public Set getPermisos() {
        return this.permisos;
    }
    
    public void setPermisos(Set permisos) {
        this.permisos = permisos;
    }




}


