package POJOs;
// Generated 06-08-2018 02:18:23 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Recibo generated by hbm2java
 */
public class Recibo  implements java.io.Serializable {


     private int noRecibo;
     private Cliente cliente;
     private Usuario usuarioByUserModificacion;
     private Usuario usuarioByUserCreacion;
     private Double monto;
     private Double imi;
     private Double ir;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private Set detallerecibos = new HashSet(0);

    public Recibo() {
    }

	
    public Recibo(int noRecibo, Cliente cliente) {
        this.noRecibo = noRecibo;
        this.cliente = cliente;
    }
    public Recibo(int noRecibo, Cliente cliente, Usuario usuarioByUserModificacion, Usuario usuarioByUserCreacion, Double monto, Double imi, Double ir, Date fechaCreacion, Date fechaModificacion, Set detallerecibos) {
       this.noRecibo = noRecibo;
       this.cliente = cliente;
       this.usuarioByUserModificacion = usuarioByUserModificacion;
       this.usuarioByUserCreacion = usuarioByUserCreacion;
       this.monto = monto;
       this.imi = imi;
       this.ir = ir;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.detallerecibos = detallerecibos;
    }
   
    public int getNoRecibo() {
        return this.noRecibo;
    }
    
    public void setNoRecibo(int noRecibo) {
        this.noRecibo = noRecibo;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Usuario getUsuarioByUserModificacion() {
        return this.usuarioByUserModificacion;
    }
    
    public void setUsuarioByUserModificacion(Usuario usuarioByUserModificacion) {
        this.usuarioByUserModificacion = usuarioByUserModificacion;
    }
    public Usuario getUsuarioByUserCreacion() {
        return this.usuarioByUserCreacion;
    }
    
    public void setUsuarioByUserCreacion(Usuario usuarioByUserCreacion) {
        this.usuarioByUserCreacion = usuarioByUserCreacion;
    }
    public Double getMonto() {
        return this.monto;
    }
    
    public void setMonto(Double monto) {
        this.monto = monto;
    }
    public Double getImi() {
        return this.imi;
    }
    
    public void setImi(Double imi) {
        this.imi = imi;
    }
    public Double getIr() {
        return this.ir;
    }
    
    public void setIr(Double ir) {
        this.ir = ir;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Set getDetallerecibos() {
        return this.detallerecibos;
    }
    
    public void setDetallerecibos(Set detallerecibos) {
        this.detallerecibos = detallerecibos;
    }




}


