package POJOs;
// Generated 06-08-2018 02:18:23 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Registrosanulados generated by hbm2java
 */
public class Registrosanulados  implements java.io.Serializable {


     private Integer idRegistrosAnulados;
     private Usuario usuario;
     private String tabla;
     private int idRegistro;
     private String motivo;
     private Date fechaAnula;

    public Registrosanulados() {
    }

	
    public Registrosanulados(Usuario usuario, String tabla, int idRegistro, String motivo) {
        this.usuario = usuario;
        this.tabla = tabla;
        this.idRegistro = idRegistro;
        this.motivo = motivo;
    }
    public Registrosanulados(Usuario usuario, String tabla, int idRegistro, String motivo, Date fechaAnula) {
       this.usuario = usuario;
       this.tabla = tabla;
       this.idRegistro = idRegistro;
       this.motivo = motivo;
       this.fechaAnula = fechaAnula;
    }
   
    public Integer getIdRegistrosAnulados() {
        return this.idRegistrosAnulados;
    }
    
    public void setIdRegistrosAnulados(Integer idRegistrosAnulados) {
        this.idRegistrosAnulados = idRegistrosAnulados;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getTabla() {
        return this.tabla;
    }
    
    public void setTabla(String tabla) {
        this.tabla = tabla;
    }
    public int getIdRegistro() {
        return this.idRegistro;
    }
    
    public void setIdRegistro(int idRegistro) {
        this.idRegistro = idRegistro;
    }
    public String getMotivo() {
        return this.motivo;
    }
    
    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }
    public Date getFechaAnula() {
        return this.fechaAnula;
    }
    
    public void setFechaAnula(Date fechaAnula) {
        this.fechaAnula = fechaAnula;
    }




}


