package POJOs;
// Generated 06-08-2018 02:18:23 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol  implements java.io.Serializable {


     private Integer idRol;
     private Usuario usuarioByUserModificacion;
     private Usuario usuarioByUserCreacion;
     private String rol;
     private String descripcion;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private Boolean regAnulado;
     private Set permisos = new HashSet(0);
     private Set usuarios = new HashSet(0);

    public Rol() {
    }

	
    public Rol(String rol) {
        this.rol = rol;
    }
    public Rol(Usuario usuarioByUserModificacion, Usuario usuarioByUserCreacion, String rol, String descripcion, Date fechaCreacion, Date fechaModificacion, Boolean regAnulado, Set permisos, Set usuarios) {
       this.usuarioByUserModificacion = usuarioByUserModificacion;
       this.usuarioByUserCreacion = usuarioByUserCreacion;
       this.rol = rol;
       this.descripcion = descripcion;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.regAnulado = regAnulado;
       this.permisos = permisos;
       this.usuarios = usuarios;
    }
   
    public Integer getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(Integer idRol) {
        this.idRol = idRol;
    }
    public Usuario getUsuarioByUserModificacion() {
        return this.usuarioByUserModificacion;
    }
    
    public void setUsuarioByUserModificacion(Usuario usuarioByUserModificacion) {
        this.usuarioByUserModificacion = usuarioByUserModificacion;
    }
    public Usuario getUsuarioByUserCreacion() {
        return this.usuarioByUserCreacion;
    }
    
    public void setUsuarioByUserCreacion(Usuario usuarioByUserCreacion) {
        this.usuarioByUserCreacion = usuarioByUserCreacion;
    }
    public String getRol() {
        return this.rol;
    }
    
    public void setRol(String rol) {
        this.rol = rol;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Boolean getRegAnulado() {
        return this.regAnulado;
    }
    
    public void setRegAnulado(Boolean regAnulado) {
        this.regAnulado = regAnulado;
    }
    public Set getPermisos() {
        return this.permisos;
    }
    
    public void setPermisos(Set permisos) {
        this.permisos = permisos;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


